language: cpp

matrix:
  include:
    #######################################################
    - os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
      install:
        - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
        - sudo apt-get install libomp-dev
    #######################################################
    - os: linux
      dist: xenial
      compiler: clang
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
      install:
        - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
        - sudo apt-get install libomp-dev
    ######################################################
    - os: osx
      osx_image: xcode10.1
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
      install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install open-mpi
    ######################################################

script:
- python scripts/lint.py
- mkdir build
- cd build
- cmake -D CMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cd ..
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then source run.sh; fi
