language: cpp

matrix:
  include:
    #######################################################
    - os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
      install:
        - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
      script:
        - python scripts/lint.py
        - mkdir build
        - cd build
        - cmake -D CMAKE_BUILD_TYPE=Release ..
        - cmake --build .
        - cd ..
        - source run.sh
    #######################################################
    - os: linux
      dist: xenial
      compiler: clang
      install:
        - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
      script:
        - python scripts/lint.py
        - mkdir build
        - cd build
        - cmake -D CMAKE_BUILD_TYPE=Release ..
        - cmake --build .
        - cd ..
    # #######################################################
    # - os: windows
    #   script:
    #     - python build.py build msvc
    #     # - python build.py test msvc # Tests failed
    #     - python build.py benchmark msvc
    # #######################################################
    # - os: osx
    #   osx_image: xcode10.1
    #   install:
    #     - HOMEBREW_NO_AUTO_UPDATE=1 brew install libomp
    #   script:
    #     - python build.py build clang
    #     # - python build.py test clang # Tests failed
    #     # - python build.py benchmark clang # Build failed
    # #######################################################
