language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-6
      env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: llvm-toolchain-trusty-3.9
          packages: clang-3.9
      env: MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: llvm-toolchain-trusty-4.0
          packages: clang-4.0
      env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: llvm-toolchain-trusty-5.0
          packages: clang-5.0
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: osx
      env: HOMEBREW_NO_AUTO_UPDATE=1
      osx_image: xcode10.1

    - os: osx
      env: HOMEBREW_NO_AUTO_UPDATE=1
      osx_image: xcode9.4

    - os: osx
      env: HOMEBREW_NO_AUTO_UPDATE=1
      osx_image: xcode9.2

before_install:
- eval "${MATRIX_EVAL}"

install:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install open-mpi libomp tbb; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install lam-runtime; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install mpich openmpi-bin libopenmpi-dev; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install libomp-dev libtbb-dev; fi

script:
- python scripts/lint.py
- mkdir build
- cd build
- cmake -D CMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cd ..
- export OMP_NUM_THREADS=4
- source run.sh

notifications:
  email: false
