language: cpp

matrix:
  include:
    #######################################################
    - os: linux
      dist: xenial
      compiler: gcc
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
      install:
        - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
        - sudo apt-get install libomp-dev
    #######################################################
    - os: linux
      dist: xenial
      compiler: clang
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
      install:
        - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
        - sudo apt-get install libomp-dev
    ######################################################
    - os: osx
      osx_image: xcode10.1
      install:
        - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
        - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade cmake
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install open-mpi
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm CLIUtils/apple/libomp
    ######################################################
    
script:
- python scripts/lint.py
- mkdir build
- cd build
- cmake -D CMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cd ..
- export OMP_NUM_THREADS=4
- source run.sh


notifications:
  email: false
