language: cpp

matrix:
  include:
    #######################################################
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      install:
       - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
       - sudo apt-get install libomp-dev libtbb-dev
    #######################################################
    - os: linux
     dist: xenial
     compiler: gcc
     addons:
       apt:
         sources: ubuntu-toolchain-r-test
         packages: g++-6
     env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
     install:
      - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
      - sudo apt-get install libomp-dev libtbb-dev
    #######################################################
    - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: g++-7
    env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    install:
     - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
     - sudo apt-get install libomp-dev libtbb-dev
    #######################################################
    - os: linux
      dist: xenial
      compiler: clang
      install:
        - sudo apt-get install lam-runtime mpich openmpi-bin libopenmpi-dev
        - sudo apt-get install libomp-dev libtbb-dev
    ######################################################
    - os: osx
      osx_image: xcode10.1
      env: HOMEBREW_NO_AUTO_UPDATE=1
      install:
        - brew install open-mpi
        - brew install libomp tbb
    ######################################################
    - os: osx
      osx_image: xcode9.4
      env: HOMEBREW_NO_AUTO_UPDATE=1
      install:
        - brew install open-mpi
        - brew install libomp tbb
    ######################################################
    - os: osx
      osx_image: xcode9
      env: HOMEBREW_NO_AUTO_UPDATE=1
      install:
        - brew install open-mpi
        - brew install libomp tbb
    ######################################################
    - os: osx
      osx_image: xcode8
      env: HOMEBREW_NO_AUTO_UPDATE=1
      install:
        - brew install open-mpi
        - brew install libomp tbb
    ######################################################

script:
- python scripts/lint.py
- mkdir build
- cd build
- cmake -D CMAKE_BUILD_TYPE=Release ..
- cmake --build .
- cd ..
- export OMP_NUM_THREADS=4
- source run.sh

notifications:
  email: false
