image:
  - Visual Studio 2012
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
    - MPI_HOME: "C:/Program Files (x86)/Microsoft SDKs/MPI"

install:
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisetup.exe'
  - MSMpiSetup.exe -unattend
  - set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
  - ps: Start-FileDownload 'https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.0/msmpisdk.msi'
  - msmpisdk.msi /passive

build_script:
  - cmd: python scripts/lint.py
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -DMPI_C_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -DMPI_C_LIBRARIES:PATH="%MPI_HOME%/Lib/x86/msmpi.lib" ^
               -DMPI_CXX_INCLUDE_PATH:PATH="%MPI_HOME%/Include" ^
               -DMPI_CXX_LIBRARIES:PATH="%MPI_HOME%/Lib/x86/msmpi.lib" ..
  - cmd: cmake --build .
  - cmd: cd ..
  - cmd: set OMP_NUM_THREADS=4
  - cmd: run.bat
